stages:
  - lint
  - test

variables:
  LANG: "en_US.UTF-8"

build_project:
  stage: lint
  script:
    - arch -x86_64 pod install --repo-update
    - Pods/SwiftLint/swiftlint DevOpsPractical8
    - ARCHIVE_PATH="$HOME/Library/Developer/Xcode/Archives/DevOpsPractica8/${CI_COMMIT_SHA}/${CI_JOB_ID}.xcarchive"
    - xcodebuild -workspace DevOpsPractical8.xcworkspace -scheme "DevOpsPractical8" clean archive -sdk iphoneos -archivePath $ARCHIVE_PATH | xcpretty --color
    - rm -rf $ARCHIVE_PATH
  tags:
    - dev-ops-practical8
  except:
    - main

unit_test:
  stage: test
  script:
    - arch -x86_64 pod install --repo-update
    - xcodebuild test -workspace "DevOpsPractical8.xcworkspace" -scheme "DevOpsPractical8" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 15 Pro" | xcpretty --color
  tags:
    - dev-ops-practical8
